services:
  - type: web
    name: rails
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s -p $PORT"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    memoryPolicy: noeviction