# Exported from Render on 2024-07-08T03:08:53Z
services:
- type: web
  name: rails
  runtime: ruby
  repo: https://github.com/Thiago-Gomes-Araujo/bootstrap
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec rails s -p 3000
version: "1"