databases:
  - name: postgres
    ipAllowList: []

services:
  - type: web
    name: rails
    env: ruby
    #plan: free # ou "starter", "standard", etc.
    buildCommand: "./bin/render-build.sh" #"bundle install && yarn install && bundle exec rake assets:precompile"
    startCommand: "bundle exec rails s -p 3000"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    mamemoryPolicy: noeviction
